// internal/api/marketplace_generate.go — G5 Marketplace draft
// generator. Spec §"CLI surface" + §"Out of scope".
//
// codex r1 P1 closures: map stdio → TransportStdioBridge (not
// native-http). Reuse PlaceholderExpander (Phase 0) with
// SkipSensitiveEnv: true so catalog-controlled secret names stay
// verbatim in the draft. G6-deferral error names today's workaround.

package api

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"mcp-local-hub/internal/config"
)

type GenerateOpts struct {
	WorkspaceFolder string
}

// GenerateDraftManifest projects a catalog entry into draft YAML.
// Returns (yaml, warnings, error). Warnings are operator-facing
// stderr lines; the YAML is operator-facing stdout content.
func GenerateDraftManifest(e *MarketplaceEntry, opts GenerateOpts) (string, []string, error) {
	switch e.Transport {
	case "stdio":
		return generateCommandDraft(e, opts, config.TransportStdioBridge)
	case "native-http":
		return generateCommandDraft(e, opts, config.TransportNativeHTTP)
	case "http":
		return generateRemoteHTTPDraft(e)
	default:
		return "", nil, fmt.Errorf("entry %q transport %q is not supported by draft generation", e.ID, e.Transport)
	}
}

// generateRemoteHTTPDraft projects an http catalog entry onto a
// transport=remote-http manifest. The catalog carries the URL but
// not headers — operators add Authorization or X-API-Key by editing
// the draft. G6 sub-PR 4 closure: prior code rejected http entries
// with a G6-deferral error.
func generateRemoteHTTPDraft(e *MarketplaceEntry) (string, []string, error) {
	if e.URL == "" {
		return "", nil, fmt.Errorf("entry %q transport=http but url is empty", e.ID)
	}
	// Bot r2 P1 closure (PR #172): catalog URLs/IDs are untrusted
	// strings. URL parsing rejects malformed https endpoints upstream,
	// but any value containing CR/LF or other line-breaking controls
	// embedded in a YAML comment line would break out of `#` and inject
	// real keys (e.g.
	// `https://x\ntransport: stdio-bridge\ncommand: cmd.exe`). Reject
	// the entry instead of mangling it so the operator sees the
	// hostile registry rather than a silently-altered draft.
	if err := rejectUnsafeMarketplaceDraftString("url", e.URL); err != nil {
		return "", nil, fmt.Errorf("entry %q url contains characters unsafe for YAML comments or draft fields — refusing to emit draft (registry may be hostile): %w", e.ID, err)
	}
	if err := rejectUnsafeMarketplaceDraftString("entry id", e.ID); err != nil {
		return "", nil, fmt.Errorf("entry id %q contains characters unsafe for YAML comments or draft fields — refusing to emit draft (registry may be hostile): %w", e.ID, err)
	}
	draft := map[string]any{
		"name":      e.ID,
		"kind":      "global",
		"transport": config.TransportRemoteHTTP,
		"url":       e.URL,
	}
	// Remote-http schema rejects daemons:; emit client_bindings only.
	// List the adapters with confirmed remote-http header support so
	// the operator removes the ones they don't want. Antigravity is
	// excluded — stdio-relay only.
	// Adapter capability matrix: every adapter that round-trips
	// Headers in clients/*.go is eligible for remote-http. Codex
	// cumulative G6 review flagged the prior 5-client list missing
	// qwen-cli, which is install-eligible and exercised by the
	// header round-trip test — the draft side must stay in sync.
	bindings := make([]map[string]any, 0, len(remoteHTTPCapableClients))
	for _, c := range remoteHTTPCapableClients {
		bindings = append(bindings, map[string]any{"client": c})
	}
	draft["client_bindings"] = bindings
	// D-3 (Tier-0) projection: carry the availability gate + install probe from
	// the catalog entry into the remote-http draft too (consistent with the
	// stdio generateCommandDraft projection). Without this, an inert (watch /
	// disabled-until-probe) http row's generate→`manifest create`→install
	// workflow would produce a remote-http manifest with no gate, so the
	// post-create readiness path would treat it as ready and bypass D-3.
	// vendored_source is intentionally NOT projected here — it is a local-stdio
	// fork concern, not a remote-URL one. The projected availability/install_probe
	// values are untrusted catalog strings, so the projection refuses unsafe runes
	// the same way the url/id fields above do.
	if err := projectAvailability(draft, e); err != nil {
		return "", nil, fmt.Errorf("entry %q has availability/install_probe characters unsafe for YAML — refusing to emit draft (registry may be hostile): %w", e.ID, err)
	}
	data, err := yaml.Marshal(draft)
	if err != nil {
		return "", nil, fmt.Errorf("yaml marshal: %w", err)
	}
	header := strings.Join([]string{
		"# Generated by `mcphub marketplace generate " + e.ID + "`.",
		"# REQUIRED edits before `mcphub manifest create`:",
		"#   1. Rename `name:` if you want a unique server id (currently the entry id).",
		"#   2. Add a `headers:` block with Authorization or X-API-Key as required",
		"#      by " + e.URL + ". Reference vault keys with ${secret:KEY} placeholders",
		"#      (resolved at install via `mcphub secrets`); never commit raw tokens.",
		"#   3. Smoke-check reachability before install:",
		"#        mcphub manifest test-remote <name>",
		"",
	}, "\n")
	return header + string(data), nil, nil
}

func generateCommandDraft(e *MarketplaceEntry, opts GenerateOpts, manifestTransport string) (string, []string, error) {
	if err := rejectUnsafeMarketplaceDraftString("entry id", e.ID); err != nil {
		return "", nil, fmt.Errorf("refusing to emit marketplace draft: %w", err)
	}
	if err := rejectUnsafeMarketplaceDraftString("command", e.Command); err != nil {
		return "", nil, fmt.Errorf("refusing to emit marketplace draft: %w", err)
	}
	if err := rejectUnsafeMarketplaceDraftStringSlice("args", e.Args); err != nil {
		return "", nil, fmt.Errorf("refusing to emit marketplace draft: %w", err)
	}
	if err := rejectUnsafeMarketplaceDraftStringMap("env", e.Env); err != nil {
		return "", nil, fmt.Errorf("refusing to emit marketplace draft: %w", err)
	}
	workspace := opts.WorkspaceFolder
	if workspace == "" {
		// codex deep-sec PR #163 lane 3 P3 closure: surface
		// os.Getwd failures instead of silently producing a draft
		// with an empty workspace placeholder. The CLI layer
		// already pre-resolves this, so this path is mostly the
		// API-direct-call fallback.
		wd, err := os.Getwd()
		if err != nil {
			return "", nil, fmt.Errorf("resolve workspace folder via os.Getwd: %w (set GenerateOpts.WorkspaceFolder explicitly)", err)
		}
		workspace = wd
	}
	// codex r6 P1 closure (PR #163): PlaceholderExpander.Expand
	// writes to UndefinedEnv for any non-sensitive ${env:VAR} that
	// resolves to empty. The map MUST be initialized to non-nil per
	// the expander's documented contract (import_vscode.go) —
	// otherwise a catalog entry with an unset non-sensitive env
	// placeholder panics with "assignment to entry in nil map".
	exp := &PlaceholderExpander{
		Workspace:        workspace,
		Getenv:           os.Getenv,
		SkipSensitiveEnv: true, // catalog is untrusted
		UndefinedEnv:     map[string]struct{}{},
	}
	args := make([]string, len(e.Args))
	for i, a := range e.Args {
		args[i] = exp.Expand(a)
	}
	env := map[string]string{}
	for k, v := range e.Env {
		env[k] = exp.Expand(v)
	}
	if err := rejectUnsafeMarketplaceDraftStringSlice("base_args", args); err != nil {
		return "", nil, fmt.Errorf("refusing to emit marketplace draft: %w", err)
	}
	if err := rejectUnsafeMarketplaceDraftStringMap("env", env); err != nil {
		return "", nil, fmt.Errorf("refusing to emit marketplace draft: %w", err)
	}
	warnings := exp.WarningsForSensitive()
	// Surface non-sensitive empty-resolution placeholders too: the
	// operator should see exactly which ${env:*} substituted to empty
	// before they pipe the draft to manifest create. Keep order
	// deterministic so the warning stream is reproducible across
	// runs.
	if len(exp.UndefinedEnv) > 0 {
		names := make([]string, 0, len(exp.UndefinedEnv))
		for name := range exp.UndefinedEnv {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			warnings = append(warnings, fmt.Sprintf("catalog references ${env:%s} which expanded to empty (variable unset in the current environment); the draft will contain an empty value at that position — edit before saving", name))
		}
	}
	// codex deep-sec PR #163 lane 2 P2 closure: workspace traversal
	// warning. A catalog entry can put `${workspaceFolder}/../foo`
	// in args or env values to break out of the workspace sandbox
	// after expansion. The operator-edit gate is the last line of
	// defense; surface the suspect placeholders explicitly so the
	// operator notices them before piping to manifest create.
	for _, raw := range collectTraversalCandidates(e.Args, e.Env) {
		if traversalSuffixContainsParentRef(raw) {
			warnings = append(warnings, fmt.Sprintf("catalog string %q uses ${workspaceFolder} followed by a parent-directory reference (..); the expanded path escapes the workspace — review before saving", raw))
		}
	}
	if err := rejectUnsafeMarketplaceWarnings(warnings); err != nil {
		return "", nil, fmt.Errorf("refusing to emit marketplace draft: %w", err)
	}
	draft := map[string]any{
		"name":      e.ID,
		"kind":      "global",
		"transport": manifestTransport,
		"command":   e.Command,
		"base_args": args,
	}
	if len(env) > 0 {
		draft["env"] = env
	}
	// Port 0 + comment-style annotation: operator MUST pick a real
	// port before `mcphub manifest create` will accept the draft.
	// Same reasoning forces them to rename `name:` if the entry id
	// collides with an installed server.
	draft["daemons"] = []map[string]any{
		{"name": "default", "port": 0},
	}
	draft["client_bindings"] = []map[string]any{
		{"client": "claude-code", "daemon": "default", "url_path": "/mcp"},
		{"client": "codex-cli", "daemon": "default", "url_path": "/mcp"},
		{"client": "cursor", "daemon": "default", "url_path": "/mcp"},
	}
	// D-2 + D-3 (Tier-0) projection: carry the vendored-source pin + availability
	// gate + install probe from the catalog entry into the drafted (and, once the
	// operator saves it, persisted) manifest. Without this the post-install
	// readiness gate would be blind to the pin/probe — it can only re-evaluate
	// fields that survive into the manifest on disk. Only the local-stdio S1 draft
	// projects these; generateRemoteHTTPDraft (S2) does not — a vendored fork is a
	// local-stdio concern, not a remote-URL one. The catalog→manifest key mapping
	// mirrors the JSON↔YAML field tags exactly.
	// Each projected value is an untrusted catalog string, so the projection
	// refuses unsafe runes the same way the id/command/args/env fields above do.
	if err := projectVendoredAndAvailability(draft, e); err != nil {
		return "", warnings, fmt.Errorf("refusing to emit marketplace draft: %w", err)
	}
	data, err := yaml.Marshal(draft)
	if err != nil {
		return "", warnings, fmt.Errorf("yaml marshal: %w", err)
	}
	// Lead the YAML with an "edit-before-save" reminder so the
	// operator cannot pipe to `manifest create` without seeing it.
	header := strings.Join([]string{
		"# Generated by `mcphub marketplace generate " + e.ID + "`.",
		"# REQUIRED edits before `mcphub manifest create`:",
		"#   1. Pick a real port for daemons[0].port (currently 0 — manifest create rejects).",
		"#   2. Rename `name:` if you want a unique server id (currently the entry id).",
		"#   3. Inspect command + base_args + env; replace any verbatim ${env:*} placeholders.",
		"",
	}, "\n")
	return header + string(data), warnings, nil
}

// projectVendoredAndAvailability writes the D-2 vendored_source + D-3
// availability / install_probe keys from the catalog entry into the drafted
// manifest map, mapping the catalog (JSON) field names onto the manifest (YAML)
// field names. Each key is emitted ONLY when the catalog entry carries it, so an
// entry without these fields produces a byte-identical draft to before Tier-0.
// Used by the local-stdio S1 draft (generateCommandDraft) — a vendored fork is a
// local-stdio concern, so this is the only path that projects vendored_source.
//
// EVERY projected value is a catalog-controlled (untrusted) string, so it MUST
// route through rejectUnsafeMarketplaceDraftString — the SAME owner the existing
// id/command/args/env/url/base_args draft fields use — before it lands in the
// draft map. Without this a hostile registry could inject C0/C1 control bytes,
// terminal escapes, or Trojan-Source bidi runes through the new vendored_source.*
// fields and have them surface verbatim in the operator's drafted YAML (bot
// catalog-r3 P2). Returns an error so generateCommandDraft refuses to emit a
// draft built from a hostile entry, mirroring how the other field rejections
// abort generation.
func projectVendoredAndAvailability(draft map[string]any, e *MarketplaceEntry) error {
	if vs := e.VendoredSource; vs != nil {
		m := map[string]any{}
		if vs.Repo != "" {
			if err := rejectUnsafeMarketplaceDraftString("vendored_source.repo", vs.Repo); err != nil {
				return err
			}
			m["repo"] = vs.Repo
		}
		if vs.PinnedRef != "" {
			if err := rejectUnsafeMarketplaceDraftString("vendored_source.pinned_ref", vs.PinnedRef); err != nil {
				return err
			}
			m["pinned_ref"] = vs.PinnedRef
		}
		if vs.InstallCmd != "" {
			if err := rejectUnsafeMarketplaceDraftString("vendored_source.install_cmd", vs.InstallCmd); err != nil {
				return err
			}
			m["install_cmd"] = vs.InstallCmd
		}
		if vs.RunCmd != "" {
			if err := rejectUnsafeMarketplaceDraftString("vendored_source.run_cmd", vs.RunCmd); err != nil {
				return err
			}
			m["run_cmd"] = vs.RunCmd
		}
		if vs.LicenseStatus != "" {
			if err := rejectUnsafeMarketplaceDraftString("vendored_source.license_status", vs.LicenseStatus); err != nil {
				return err
			}
			m["license_status"] = vs.LicenseStatus
		}
		draft["vendored_source"] = m
	}
	// required_secrets (opt-in install gate) is projected ONLY on the local-stdio
	// S1 draft — a required LOCAL-ENV secret is a local-stdio concern (the daemon
	// reads it from its env), so generateRemoteHTTPDraft (S2) does NOT project it
	// (a remote endpoint's credentials ride url/headers ${secret:KEY} placeholders,
	// which are gated by the remote-http secret path, not this list). Carrying it
	// into the persisted manifest is what lets the post-install AdmissionCheck /
	// readiness gate re-evaluate the required-secret block. Each key is a catalog-
	// controlled (untrusted) string, so the slice routes through the SAME
	// rejectUnsafeMarketplaceDraftStringSlice owner every other untrusted draft
	// slice uses. Emitted ONLY when present, so an entry without it drafts a
	// byte-identical manifest.
	if len(e.RequiredSecrets) > 0 {
		if err := rejectUnsafeMarketplaceDraftStringSlice("required_secrets", e.RequiredSecrets); err != nil {
			return err
		}
		draft["required_secrets"] = e.RequiredSecrets
	}
	return projectAvailability(draft, e)
}

// projectAvailability writes ONLY the D-3 availability / install_probe keys from
// the catalog entry into the drafted manifest map. It is the shared owner both
// the local-stdio S1 draft (via projectVendoredAndAvailability) and the
// remote-http S2 draft (generateRemoteHTTPDraft) call, so an inert http row's
// drafted manifest carries the SAME gate the stdio path projects — without that,
// a watch/disabled http entry's generate→create→install workflow would bypass
// the D-3 readiness gate (the persisted remote-http manifest would look ready).
// vendored_source is deliberately NOT projected here: it is a local-stdio fork
// concern, not a remote-URL one. Each key is emitted ONLY when present, so an
// entry without the D-3 fields produces a byte-identical draft to before.
//
// availability + every install_probe binaries[]/files[] value is catalog-
// controlled (untrusted), so each routes through rejectUnsafeMarketplaceDraftString
// (the same owner the existing draft fields use) before it lands in the draft map,
// so a hostile registry cannot inject control/escape/bidi runes through the new
// D-3 fields (bot catalog-r3 P2). Returns an error so both draft paths
// (generateCommandDraft via projectVendoredAndAvailability, generateRemoteHTTPDraft
// directly) refuse to emit a draft built from a hostile entry.
func projectAvailability(draft map[string]any, e *MarketplaceEntry) error {
	if e.Availability != "" {
		if err := rejectUnsafeMarketplaceDraftString("availability", e.Availability); err != nil {
			return err
		}
		draft["availability"] = e.Availability
	}
	if p := e.InstallProbe; p != nil {
		m := map[string]any{}
		if len(p.Binaries) > 0 {
			if err := rejectUnsafeMarketplaceDraftStringSlice("install_probe.binaries", p.Binaries); err != nil {
				return err
			}
			m["binaries"] = p.Binaries
		}
		if len(p.Files) > 0 {
			if err := rejectUnsafeMarketplaceDraftStringSlice("install_probe.files", p.Files); err != nil {
				return err
			}
			m["files"] = p.Files
		}
		if len(p.FileGlobs) > 0 {
			if err := rejectUnsafeMarketplaceDraftStringSlice("install_probe.file_globs", p.FileGlobs); err != nil {
				return err
			}
			m["file_globs"] = p.FileGlobs
		}
		draft["install_probe"] = m
	}
	return nil
}

// collectTraversalCandidates returns every string from args + env
// values that mentions `${workspaceFolder}` literally. Order is
// stable: args first (in order), then env values sorted by key, so
// the warning stream is reproducible across runs.
func collectTraversalCandidates(args []string, env map[string]string) []string {
	out := make([]string, 0, len(args)+len(env))
	for _, a := range args {
		if strings.Contains(a, "${workspaceFolder}") {
			out = append(out, a)
		}
	}
	keys := make([]string, 0, len(env))
	for k, v := range env {
		if strings.Contains(v, "${workspaceFolder}") {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)
	for _, k := range keys {
		out = append(out, env[k])
	}
	return out
}

// traversalSuffixContainsParentRef returns true when the part of `s`
// following `${workspaceFolder}` references a parent directory via
// a `..` path segment. A `..` segment after the placeholder is the
// load-bearing signal: a catalog entry like
// `${workspaceFolder}/../../etc/passwd` resolves outside the
// workspace once expanded, while a legitimate
// `${workspaceFolder}/db.sqlite` does not.
//
// Match rules (case-insensitive on the path separator, but the
// `..` segment itself is byte-literal):
//   - any of `/../`, `\..\`, `/..\`, `\../` after the placeholder
//   - a trailing `/..` or `\..` after the placeholder
//
// codex deep-sec PR #163 lane 2 P2 closure.
func traversalSuffixContainsParentRef(s string) bool {
	const ph = "${workspaceFolder}"
	idx := strings.Index(s, ph)
	if idx < 0 {
		return false
	}
	tail := s[idx+len(ph):]
	if tail == "" {
		return false
	}
	for _, pat := range []string{"/../", `\..\`, `/..\`, `\../`} {
		if strings.Contains(tail, pat) {
			return true
		}
	}
	for _, suf := range []string{"/..", `\..`} {
		if strings.HasSuffix(tail, suf) {
			return true
		}
	}
	return false
}

// containsUnsafeYAMLCommentRunes reports whether s holds any terminal/draft
// unsafe rune when interpolated into YAML comment text.
func containsUnsafeYAMLCommentRunes(s string) bool {
	return containsUnsafeMarketplaceText(s)
}
