// internal/api/marketplace_generate.go — G5 Marketplace draft
// generator. Spec §"CLI surface" + §"Out of scope".
//
// codex r1 P1 closures: map stdio → TransportStdioBridge (not
// native-http). Reuse PlaceholderExpander (Phase 0) with
// SkipSensitiveEnv: true so catalog-controlled secret names stay
// verbatim in the draft. G6-deferral error names today's workaround.

package api

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"

	"mcp-local-hub/internal/config"
)

type GenerateOpts struct {
	WorkspaceFolder string
}

// GenerateDraftManifest projects a catalog entry into draft YAML.
// Returns (yaml, warnings, error). Warnings are operator-facing
// stderr lines; the YAML is operator-facing stdout content.
func GenerateDraftManifest(e *MarketplaceEntry, opts GenerateOpts) (string, []string, error) {
	if e.Transport == "http" {
		return "", nil, fmt.Errorf("entry %q is http transport — G6 (Remote MCP manifests) is deferred to v0.4.x; today's only workaround is to wait for G6 or hand-author a local stdio wrapper that proxies to %s",
			e.ID, e.URL)
	}
	if e.Transport != "stdio" {
		return "", nil, fmt.Errorf("entry %q transport %q is not supported by draft generation", e.ID, e.Transport)
	}
	workspace := opts.WorkspaceFolder
	if workspace == "" {
		if wd, err := os.Getwd(); err == nil {
			workspace = wd
		}
	}
	exp := &PlaceholderExpander{
		Workspace:        workspace,
		Getenv:           os.Getenv,
		SkipSensitiveEnv: true, // catalog is untrusted
	}
	args := make([]string, len(e.Args))
	for i, a := range e.Args {
		args[i] = exp.Expand(a)
	}
	env := map[string]string{}
	for k, v := range e.Env {
		env[k] = exp.Expand(v)
	}
	warnings := exp.WarningsForSensitive()
	draft := map[string]any{
		"name":      e.ID,
		"kind":      "global",
		"transport": config.TransportStdioBridge,
		"command":   e.Command,
		"base_args": args,
	}
	if len(env) > 0 {
		draft["env"] = env
	}
	// Port 0 + comment-style annotation: operator MUST pick a real
	// port before `mcphub manifest create` will accept the draft.
	// Same reasoning forces them to rename `name:` if the entry id
	// collides with an installed server.
	draft["daemons"] = []map[string]any{
		{"name": "default", "port": 0},
	}
	draft["client_bindings"] = []map[string]any{
		{"client": "claude-code", "daemon": "default", "url_path": "/mcp"},
		{"client": "codex-cli", "daemon": "default", "url_path": "/mcp"},
		{"client": "cursor", "daemon": "default", "url_path": "/mcp"},
	}
	data, err := yaml.Marshal(draft)
	if err != nil {
		return "", warnings, fmt.Errorf("yaml marshal: %w", err)
	}
	// Lead the YAML with an "edit-before-save" reminder so the
	// operator cannot pipe to `manifest create` without seeing it.
	header := strings.Join([]string{
		"# Generated by `mcphub marketplace generate " + e.ID + "`.",
		"# REQUIRED edits before `mcphub manifest create`:",
		"#   1. Pick a real port for daemons[0].port (currently 0 — manifest create rejects).",
		"#   2. Rename `name:` if you want a unique server id (currently the entry id).",
		"#   3. Inspect command + base_args + env; replace any verbatim ${env:*} placeholders.",
		"",
	}, "\n")
	return header + string(data), warnings, nil
}
