package archguard

import (
	"strings"
	"testing"
)

func TestVerifyAcceptsWorkerClassifiedOnlyInRegistry(t *testing.T) {
	violation := sampleViolation("worker", 0)
	violation.Kind = KindWorker
	violation.Fingerprint = Fingerprint(violation)

	workers := Workers{SchemaVersion: 1, Entries: []WorkerRecord{{
		Fingerprint:  violation.Fingerprint,
		Component:    "archguard",
		Owner:        "architecture",
		Start:        "F",
		Cancel:       "context cancellation",
		Join:         "wait group",
		BoundedBy:    "request deadline",
		ContractTest: "worker_test.go",
		WorkPackage:  "WP-11A",
	}}}
	got := Verify(
		reportOf(violation),
		Baseline{SchemaVersion: 1, GeneratedFrom: "base"},
		workers,
		VerifyOptions{Now: mustDate(t, "2026-08-25")},
	)
	if !got.OK() || len(got.New) != 0 {
		t.Fatalf("verification=%#v, want registry-only worker classification to pass", got)
	}
}

func TestGeneratedMarkerInsideBlockCommentDoesNotSuppressProductionRules(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x.go": `/*
// Code generated by example. DO NOT EDIT.
*/
package x

var mutable = 1
`,
	})
	policy := mustLoadPolicyForTest(t)
	policy.SourceRoots = []string{"internal"}
	got := violationsOfKind(mustScan(t, root, policy), KindMutableGlobal)
	if len(got) != 1 || got[0].Location.Symbol != "mutable" {
		t.Fatalf("got=%#v, block-comment text must not mark a file generated", got)
	}
}

func TestBuildDirectiveInsideBlockCommentDoesNotMarkFileTestOnly(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x.go": `/*
//go:build test_state_path_env
*/
package x

var mutable = 1
`,
	})
	policy := mustLoadPolicyForTest(t)
	policy.SourceRoots = []string{"internal"}
	policy.TestOnlyBuildTags = []string{"test_state_path_env"}
	got := violationsOfKind(mustScan(t, root, policy), KindMutableGlobal)
	if len(got) != 1 || got[0].Location.Symbol != "mutable" {
		t.Fatalf("got=%#v, block-comment text must not act as a build directive", got)
	}
}

func TestScanRejectsPolicyModuleMismatch(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x.go": "package x\n",
	})
	policy := mustLoadPolicyForTest(t)
	policy.SourceRoots = []string{"internal"}
	policy.Module = "wrong-module"
	_, err := Scan(t.Context(), ScanOptions{Root: root, Policy: policy})
	if err == nil || !strings.Contains(err.Error(), "policy module") || !strings.Contains(err.Error(), "mcp-local-hub") {
		t.Fatalf("error=%v, want policy/go.mod module mismatch", err)
	}
}

func TestUnaliasedLocalImportUsesDeclaredPackageName(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/ctor/v2/ctor.go": `package ctor
func New() any { return nil }
`,
		"internal/x/x.go": `package x
import "mcp-local-hub/internal/ctor/v2"
func F() { _ = ctor.New() }
`,
	})
	policy := mustLoadPolicyForTest(t)
	policy.SourceRoots = []string{"internal"}
	policy.APIConstructors = []SymbolRule{{ImportPath: "mcp-local-hub/internal/ctor/v2", Symbol: "New"}}
	got := violationsOfKind(mustScan(t, root, policy), KindAPIConstruction)
	if len(got) != 1 || got[0].Location.Symbol != "F" {
		t.Fatalf("got=%#v, want the declared package name ctor to resolve", got)
	}
}

func TestExternalConstructorPackageRequiresExplicitAlias(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x.go": `package x
import "example.com/ctor/v2"
func F() { _ = ctor.New() }
`,
	})
	policy := mustLoadPolicyForTest(t)
	policy.SourceRoots = []string{"internal"}
	policy.APIConstructors = []SymbolRule{{ImportPath: "example.com/ctor/v2", Symbol: "New"}}
	got := violationsOfKind(mustScan(t, root, policy), KindAPIConstruction)
	if len(got) != 1 || !strings.Contains(got[0].Message, "explicit alias") {
		t.Fatalf("got=%#v, want fail-closed explicit-alias finding", got)
	}
}

func TestExplicitExternalConstructorAliasStillMatchesCalls(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x.go": `package x
import ctor "example.com/ctor/v2"
func F() { _ = ctor.New() }
`,
	})
	policy := mustLoadPolicyForTest(t)
	policy.SourceRoots = []string{"internal"}
	policy.APIConstructors = []SymbolRule{{ImportPath: "example.com/ctor/v2", Symbol: "New"}}
	got := violationsOfKind(mustScan(t, root, policy), KindAPIConstruction)
	if len(got) != 1 || got[0].Location.Symbol != "F" || strings.Contains(got[0].Message, "explicit alias") {
		t.Fatalf("got=%#v, want the explicitly aliased call finding", got)
	}
}
