package archguard

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestLoadPolicyRejectsTrailingDocument(t *testing.T) {
	path := writeTempFile(t, validPolicyJSON+"\n"+validPolicyJSON)
	_, err := LoadPolicy(path)
	if err == nil || !strings.Contains(err.Error(), "trailing") {
		t.Fatalf("error=%v, want trailing document rejection", err)
	}
}

func TestLoadPolicyRejectsSourceRootEscape(t *testing.T) {
	policy := strings.Replace(validPolicyJSON, `"source_roots": ["."]`, `"source_roots": ["../outside"]`, 1)
	_, err := LoadPolicy(writeTempFile(t, policy))
	if err == nil || !strings.Contains(err.Error(), "source_roots") {
		t.Fatalf("error=%v, want source_roots rejection", err)
	}
}

func TestGeneratedMarkerBeforePackageIsRecognized(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/generated.go": "// Copyright example\n\n// Code generated by generator. DO NOT EDIT.\npackage x\n// PR #99\nvar mutable = 1\n" + strings.Repeat("\n", 20),
	})
	p := mustLoadPolicyForTest(t)
	p.SourceRoots = []string{"internal"}
	p.FileBudgets = FileBudgets{ProductionAdvisoryLines: 2, ProductionHardLines: 3, TestReviewLines: 3}
	report := mustScan(t, root, p)
	for _, kind := range []ViolationKind{KindMutableGlobal, KindHistoryComment, KindFileBudget} {
		if got := violationsOfKind(report, kind); len(got) != 0 {
			t.Fatalf("kind=%s got=%#v", kind, got)
		}
	}
}

func TestEmbeddedDocumentAggregatesStringConcatenation(t *testing.T) {
	left := "# Heading\n" + strings.Repeat("a", 60)
	right := "\n| A | B |\n|---|---|\n" + strings.Repeat("b", 60)
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x.go": "package x\nconst workflow = `" + left + "` + \"`\" + `" + right + "`\n",
	})
	p := mustLoadPolicyForTest(t)
	p.SourceRoots = []string{"internal"}
	p.EmbeddedDocumentMinBytes = 100
	got := violationsOfKind(mustScan(t, root, p), KindEmbeddedDocument)
	if len(got) != 1 || got[0].Location.Symbol != "workflow" || got[0].Metric < 100 {
		t.Fatalf("got=%#v", got)
	}
}

func TestWorkersIgnoreTestAndGeneratedFiles(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x_test.go":    "package x\nfunc TestX(){ go func(){}() }\n",
		"internal/x/generated.go": "// Code generated by test. DO NOT EDIT.\npackage x\nfunc F(){ go func(){}() }\n",
	})
	p := mustLoadPolicyForTest(t)
	p.SourceRoots = []string{"internal"}
	if got := violationsOfKind(mustScan(t, root, p), KindWorker); len(got) != 0 {
		t.Fatalf("workers=%#v", got)
	}
}

func TestWorkerRuleDistinguishesAnonymousWorkersInOneFunction(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x.go": "package x\nfunc F(){ go func(){ println(1) }(); go func(){ println(2) }() }\n",
	})
	p := mustLoadPolicyForTest(t)
	p.SourceRoots = []string{"internal"}
	workers := violationsOfKind(mustScan(t, root, p), KindWorker)
	if len(workers) != 2 {
		t.Fatalf("workers=%#v", workers)
	}
	if workers[0].Fingerprint == workers[1].Fingerprint {
		t.Fatalf("anonymous workers collapsed to %s", workers[0].Fingerprint)
	}
}

func TestVerifyAcceptsLegacyWorkerInBaseline(t *testing.T) {
	v := sampleViolation("worker", 0)
	v.Kind = KindWorker
	v.Fingerprint = Fingerprint(v)
	baseline := baselineOf(v, "2027-01-01")
	baseline.GeneratedFrom = "base-sha"
	got := Verify(reportOf(v), baseline, Workers{SchemaVersion: 1}, VerifyOptions{Now: mustDate(t, "2026-08-24")})
	if !got.OK() {
		t.Fatalf("got=%#v", got)
	}
}

func TestVerifyRejectsWorkerInBaselineAndRegistry(t *testing.T) {
	v := sampleViolation("worker", 0)
	v.Kind = KindWorker
	v.Fingerprint = Fingerprint(v)
	workers := Workers{SchemaVersion: 1, Entries: []WorkerRecord{{
		Fingerprint:  v.Fingerprint,
		Component:    "x",
		Owner:        "owner",
		Start:        "F",
		Cancel:       "context",
		Join:         "wait",
		BoundedBy:    "timeout",
		ContractTest: "x_test.go",
		WorkPackage:  "WP-11",
	}}}
	baseline := baselineOf(v, "2027-01-01")
	baseline.GeneratedFrom = "base-sha"
	got := Verify(reportOf(v), baseline, workers, VerifyOptions{Now: mustDate(t, "2026-08-24")})
	if len(got.Workers) != 1 || !strings.Contains(got.Workers[0].Problem, "both") {
		t.Fatalf("got=%#v", got)
	}
}

func TestGlobTrailingDoubleStarMatchesPackageRoot(t *testing.T) {
	if !matchGlob("internal/api/**", "internal/api") {
		t.Fatal("trailing /** must match the package root")
	}
	if !matchGlob("internal/api/**", "internal/api/sub") {
		t.Fatal("trailing /** must match descendants")
	}
}

func TestImportRuleUsesRepositoryRelativeLocalImportPath(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/cli/x.go": "package cli\nimport _ \"mcp-local-hub/internal/gui\"\n",
	})
	p := mustLoadPolicyForTest(t)
	p.SourceRoots = []string{"internal"}
	p.ImportRules = []ImportRule{{From: []string{"internal/cli/**"}, Deny: []string{"internal/gui/**"}}}
	got := violationsOfKind(mustScan(t, root, p), KindImport)
	if len(got) != 1 {
		t.Fatalf("got=%#v", got)
	}
}

func TestFileBudgetFingerprintSurvivesThresholdClassChange(t *testing.T) {
	fingerprint := func(lines int) string {
		root := newFixtureRepo(t, map[string]string{
			"internal/x/x.go": "package x\n" + strings.Repeat("\n", lines-1),
		})
		p := mustLoadPolicyForTest(t)
		p.SourceRoots = []string{"internal"}
		p.FileBudgets = FileBudgets{ProductionAdvisoryLines: 2, ProductionHardLines: 4, TestReviewLines: 4}
		got := violationsOfKind(mustScan(t, root, p), KindFileBudget)
		if len(got) != 1 {
			t.Fatalf("lines=%d got=%#v", lines, got)
		}
		return got[0].Fingerprint
	}
	if got, want := fingerprint(3), fingerprint(5); got != want {
		t.Fatalf("threshold class changed fingerprint: got=%s want=%s", got, want)
	}
}

func TestLoadPolicyRejectsEmbeddedParentTraversal(t *testing.T) {
	policy := strings.Replace(validPolicyJSON, `"source_roots": ["."]`, `"source_roots": ["cmd/../internal"]`, 1)
	_, err := LoadPolicy(writeTempFile(t, policy))
	if err == nil || !strings.Contains(err.Error(), "source_roots") {
		t.Fatalf("error=%v, want embedded parent traversal rejection", err)
	}
}

func TestWorkerFingerprintsDistinguishMethodsWithSameName(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x.go": `package x
	type A struct{}
	type B struct{}
	func (A) Start(){ go func(){}() }
	func (B) Start(){ go func(){}() }
`,
	})
	p := mustLoadPolicyForTest(t)
	p.SourceRoots = []string{"internal"}
	workers := violationsOfKind(mustScan(t, root, p), KindWorker)
	if len(workers) != 2 {
		t.Fatalf("workers=%#v", workers)
	}
	if workers[0].Location.Symbol == workers[1].Location.Symbol || workers[0].Fingerprint == workers[1].Fingerprint {
		t.Fatalf("method workers collided: %#v", workers)
	}
}

func TestRuleDetectsProductionTestHookMethod(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x.go": "package x\ntype A struct{}\nfunc (A) SetClockForTest(){}\n",
	})
	p := mustLoadPolicyForTest(t)
	p.SourceRoots = []string{"internal"}
	got := violationsOfKind(mustScan(t, root, p), KindProductionTestHook)
	if len(got) != 1 || got[0].Location.Symbol != "A.SetClockForTest" {
		t.Fatalf("got=%#v", got)
	}
}

func TestLoadBaselineRejectsMissingGeneratedFrom(t *testing.T) {
	_, err := LoadBaseline(writeTempFile(t, `{"schema_version":1,"entries":[]}`))
	if err == nil || !strings.Contains(err.Error(), "generated_from") {
		t.Fatalf("error=%v, want generated_from rejection", err)
	}
}

func TestLoadBaselineRejectsFingerprintMismatch(t *testing.T) {
	v := sampleViolation("x", 0)
	v.Fingerprint = strings.Repeat("0", 64)
	body, err := json.Marshal(Baseline{SchemaVersion: 1, GeneratedFrom: "abc", Entries: []BaselineEntry{{
		Violation: v, Owner: "owner", WorkPackage: "WP-11", RemoveBy: "2027-01-01", Reason: "legacy",
	}}})
	if err != nil {
		t.Fatal(err)
	}
	_, err = LoadBaseline(writeTempFile(t, string(body)))
	if err == nil || !strings.Contains(err.Error(), "fingerprint") {
		t.Fatalf("error=%v, want fingerprint mismatch", err)
	}
}

func TestLoadPolicyRejectsEmptyImportRule(t *testing.T) {
	policy := strings.Replace(validPolicyJSON,
		`{"from": ["internal/cli"], "deny": ["mcp-local-hub/internal/gui"]}`,
		`{"from": [], "deny": ["internal/gui/**"]}`,
		1,
	)
	_, err := LoadPolicy(writeTempFile(t, policy))
	if err == nil || !strings.Contains(err.Error(), "import_rules") {
		t.Fatalf("error=%v, want import_rules rejection", err)
	}
}

func TestWorkerFingerprintsDistinguishPackageLevelFunctionLiterals(t *testing.T) {
	root := newFixtureRepo(t, map[string]string{
		"internal/x/x.go": "package x\nvar first = func(){ go run() }\nvar second = func(){ go run() }\nfunc run(){}\n",
	})
	p := mustLoadPolicyForTest(t)
	p.SourceRoots = []string{"internal"}
	workers := violationsOfKind(mustScan(t, root, p), KindWorker)
	if len(workers) != 2 {
		t.Fatalf("workers=%#v", workers)
	}
	if workers[0].Location.Symbol == workers[1].Location.Symbol || workers[0].Fingerprint == workers[1].Fingerprint {
		t.Fatalf("package-level function workers collided: %#v", workers)
	}
}

func TestGlobPatternsUsedByRepositoryPolicy(t *testing.T) {
	tests := []struct {
		pattern string
		value   string
		want    bool
	}{
		{"internal/api/**/*_test.go", "internal/api/install_test.go", true},
		{"internal/api/**/*_test.go", "internal/api/sub/install_test.go", true},
		{"internal/api/**/*_test.go", "internal/api/install.go", false},
		{"**/*_test.go", "x_test.go", true},
		{"**/*_test.go", "internal/x/x_test.go", true},
		{"**/testdata/**", "internal/x/testdata/fixture.go", true},
	}
	for _, tc := range tests {
		if got := matchGlob(tc.pattern, tc.value); got != tc.want {
			t.Errorf("matchGlob(%q, %q)=%v, want %v", tc.pattern, tc.value, got, tc.want)
		}
	}
}

func TestLoadPolicyRejectsEmptyRegexPattern(t *testing.T) {
	policy := strings.Replace(validPolicyJSON, `"allowed_global_name_patterns": ["^Err[A-Z]"]`, `"allowed_global_name_patterns": [""]`, 1)
	_, err := LoadPolicy(writeTempFile(t, policy))
	if err == nil || !strings.Contains(err.Error(), "allowed_global_name_patterns") {
		t.Fatalf("error=%v, want empty regex rejection", err)
	}
}
