import { useEffect, useRef, useState } from "preact/hooks";

export interface RouterState {
  screen: string;
  query: string;  // the raw query-string after "?", empty if none
}

function parse(defaultScreen: string): RouterState {
  const hash = window.location.hash || `#/${defaultScreen}`;
  const afterPrefix = hash.replace(/^#\//, "");
  const [screenRaw, queryRaw = ""] = afterPrefix.split("?", 2);
  return {
    screen: screenRaw || defaultScreen,
    query: queryRaw,
  };
}

// useRouter is a minimal hash router. Returns {screen, query} as stable
// strings. The guard receives the TARGET RouterState BEFORE it is
// committed to internal state. Returning false reverts the hash via
// history.replaceState; internal state NEVER moves to the declined
// target. This is critical for AddServer's identity-change flow: a
// dirty-cancelled ?name=a → ?name=b navigation must not update editName,
// or the load effect would fire and fetch b against the user's intent.
//
// R3 correction: no suppression flag. replaceState with a hash does NOT
// fire hashchange (per HTML spec), so the "follow-up event we suppress"
// doesn't exist. The earlier draft kept suppressRef=true forever after
// the first decline, poisoning all future navigations. Correct pattern
// is just replaceState; the next real hashchange (from user action) is
// not synthetically generated by us.
//
// R2b-Q3 correction: guard is stored in a ref so callers can pass an
// inline arrow (typical React/Preact pattern) without re-subscribing
// the hashchange listener on every render. The ref always points at
// the latest guard closure — no stale-closure hazard, no double-fire
// window between removeEventListener and addEventListener.
//
// R2b-Q4 correction: e.oldURL can be the empty string (happy-dom sends
// "" for the first hashchange from a blank page; browsers do not
// guarantee it is a valid URL). new URL("") throws. Guard against
// that so the revert path never silently no-ops.
export function useRouter(
  defaultScreen: string,
  guard?: (target: RouterState) => boolean,
): RouterState {
  const [state, setState] = useState<RouterState>(() => parse(defaultScreen));
  const guardRef = useRef(guard);
  guardRef.current = guard;

  useEffect(() => {
    const onHash = (e: HashChangeEvent) => {
      const target = parse(defaultScreen);
      const g = guardRef.current;
      if (g && !g(target)) {
        // replaceState does NOT fire hashchange — no suppress-flag needed.
        // The URL reverts, internal state stays, and the next real
        // user-initiated navigation fires hashchange cleanly.
        //
        // Extract only the hash fragment from oldURL so the replaceState
        // call is always same-origin-safe. Fall back to the current
        // defaultScreen root if oldURL is empty or unparseable (happy-dom
        // sends "" on first-nav; bad browser contracts may do the same).
        let oldHash = `#/${defaultScreen}`;
        try {
          const parsed = new URL(e.oldURL).hash;
          if (parsed) oldHash = parsed;
        } catch {
          // empty or malformed oldURL; fall through to defaultScreen root
        }
        window.history.replaceState(null, "", oldHash);
        return;
      }
      setState(target);
    };
    window.addEventListener("hashchange", onHash);
    return () => window.removeEventListener("hashchange", onHash);
    // Intentionally NOT depending on `guard` — it lives in guardRef so
    // identity churn (fresh inline arrow per render) doesn't resubscribe.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [defaultScreen]);

  return state;
}
