import { useEffect, useState } from "preact/hooks";

export interface RouterState {
  screen: string;
  query: string;  // the raw query-string after "?", empty if none
}

function parse(defaultScreen: string): RouterState {
  const hash = window.location.hash || `#/${defaultScreen}`;
  const afterPrefix = hash.replace(/^#\//, "");
  const [screenRaw, queryRaw = ""] = afterPrefix.split("?", 2);
  return {
    screen: screenRaw || defaultScreen,
    query: queryRaw,
  };
}

// useRouter is a minimal hash router. Returns {screen, query} as stable
// strings. The guard receives the TARGET RouterState BEFORE it is
// committed to internal state. Returning false reverts the hash via
// history.replaceState; internal state NEVER moves to the declined
// target. This is critical for AddServer's identity-change flow: a
// dirty-cancelled ?name=a → ?name=b navigation must not update editName,
// or the load effect would fire and fetch b against the user's intent.
//
// R3 correction: no suppression flag. replaceState with a hash does NOT
// fire hashchange (per HTML spec), so the "follow-up event we suppress"
// doesn't exist. The earlier draft kept suppressRef=true forever after
// the first decline, poisoning all future navigations. Correct pattern
// is just replaceState; the next real hashchange (from user action) is
// not synthetically generated by us.
export function useRouter(
  defaultScreen: string,
  guard?: (target: RouterState) => boolean,
): RouterState {
  const [state, setState] = useState<RouterState>(() => parse(defaultScreen));

  useEffect(() => {
    const onHash = (e: HashChangeEvent) => {
      const target = parse(defaultScreen);
      if (guard && !guard(target)) {
        // replaceState does NOT fire hashchange — no suppress-flag needed.
        // The URL reverts, internal state stays, and the next real
        // user-initiated navigation fires hashchange cleanly.
        // Extract only the hash fragment from oldURL so the replaceState
        // call is always same-origin-safe (full oldURL may carry a
        // different origin string in test environments).
        const oldHash = new URL(e.oldURL).hash || "#/";
        window.history.replaceState(null, "", oldHash);
        return;
      }
      setState(target);
    };
    window.addEventListener("hashchange", onHash);
    return () => window.removeEventListener("hashchange", onHash);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [guard, defaultScreen]);

  return state;
}
